name: Terraform CI Workflow

on:
  workflow_call:

jobs:
  validate:
    name: Terraform Validate
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.tf-validate.yaml

  lint:
    name: Terraform Lint
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.tf-lint.yaml

  checkov:
    name: Checkov
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.tf-checkov.yaml

  fmt:
    name: Terraform Fmt
    if: github.event_name == 'pull_request'
    needs: [validate, lint, checkov]
    uses: ./.github/workflows/.tf-fmt.yaml

  docs:
    name: Generate Docs
    if: github.event_name == 'pull_request'
    needs: [validate, lint, checkov]
    uses: ./.github/workflows/.tf-docs.yaml

  release:
    name: Generate Release
    if: github.event_name == 'push'
    uses: ./.github/workflows/.tf-release.yaml
