name: Terraform Docs Generate

on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render and push Docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        git-push: "true"
