name: Terraform Run fmt

on:
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: fmt
        run: |
          terraform fmt -no-color -write=true -list=true -recursive

      - uses: stefanzweifel/git-auto-commit-action@v5
