name: Terraform Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
      continue-on-error: true
