name: Terraform fmt and validate

on:
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: fmt
        run: |
          terraform fmt -write=false -diff -check -recursive
  
  validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: validate
        run: |
          terraform init
          terraform validate