name: Terraform Validate

on:
  workflow_call:

jobs:  
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: validate
        run: |
          terraform init
          terraform validate