name: Terraform Validate

on:
  workflow_call:

jobs:  
  validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: validate
        run: |
          terraform init
          terraform validate